# Generated by Django 4.2 on 2023-05-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospedaje', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos',
            new_name='DatosHuesped',
        ),
    ]
